language: rust
os:
  - windows
  - linux
rust:
  - stable
before_deploy:
  - cargo build --release
deploy:
  provider: releases
  api_key:
    secure: "VZSM1VXmfc4X1EKrFD7VS9h7KJp2HfSsRpK01rxkH0Of9n0uMhltZr9o1ryw6MJ5TJmBc6no+e6S8kU/2ETwh1AjPa5/PM2Ifvb7CbhrC5KnipuAUJsPEG3F89Nxud4RwEZi2KyEQFDZSxLpUNx2YvelRJMz/t1rjLI1/5Ov6xIq/BuI09LMHY6GmNm0SLvwcmxwlxYDko3G0Mdjz7kX8PZrj3xBmvyZ0zftp0vrN8EZdK6qiVUv7VYOHX/IErCqyN1CNLWJV9x6ajdhLe8dZNYXAd1Z60P7AkfAsPOK/DLx0A8tgRYcwVQYdtioJHUojwuJvwz/43c1ZATlTNjCS5RrCrG74aYyyIU4ucyo0UI7jkw4I24ZKCLwjja0jbfcJ0lCgD3jsutRecgoMg2bkNPRoakiH20Nftjkqf5f7/eHAaEp9LYUQQ1DkO13mhR1XvItRRg8FSJ7be2cnZL6y4NOCRMsLho9R0rFN3oIkWc+cun/AOOhvXZPl32gDnOmVyC2rV/WePQdQcRGwoOsSQQ4kofSbCR3JYSRsD4BvegZ0hTmM7vFnNj8nMXGIm1kLbU9j/M5u3WlA4U6Er/LfXbLyXQaTFIhoZ12wOx3QQrHrKQJSsuViUX8h8mbOA6x++kgmNjkrLFTRw+trwpPLAxjqwMg5TRHhPhOhrpYHBA="
  file: target/release/releases-test
  on:
    repo: krdln/releases-test
